## 应用名称
spring:
  application:
    name: sim

  ## Redis 配置
  redis:
    host: 192.168.30.166
    ## Redis服务器连接端口
    port: 6379
    password:




## 应用服务 WEB 访问端口
server:
  port: 8081

## 设置日志级别
logging:
  level:
    web: debug

## sim webSocket 访问端口
websocket:
  port: 8899



