logging:
    level:
        web: debug
server:
    port: 8081
spring:
    application:
        name: sim
    redis:
        host: 192.168.30.166
        password:
        port: 6379
websocket:
    port: 8899
